# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddcomment():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addcomment(self):
    self.driver.get("https://www.testgreencity.ga/GreenCityClient/")
    self.driver.set_window_size(1440, 819)
    self.driver.find_element(By.LINK_TEXT, "Eco news").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gallery-view-li-active:nth-child(1) .list-image-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comment-width").send_keys("Cool news")
    self.driver.find_element(By.CSS_SELECTOR, ".primary-global-button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".comment-body-wrapper:nth-child(1) .comment-text").text == "Cool news"
  
