# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatenews():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createnews(self):
    self.driver.get("https://www.testgreencity.ga/GreenCityClient/")
    self.driver.set_window_size(1440, 819)
    self.driver.find_element(By.LINK_TEXT, "Eco news").click()
    self.driver.find_element(By.ID, "create-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > .ng-invalid").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > .ng-invalid").send_keys("Hello world")
    self.driver.find_element(By.CSS_SELECTOR, ".left-form-column").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ql-toolbar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor > p").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Content 111111111111111</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, "label > span").click()
    self.driver.find_element(By.ID, "upload").send_keys("/Users/valentusik/Downloads/2f14df0-------.jpg")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
  
