# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatenewsnegative():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createnewsnegative(self):
    self.driver.get("https://www.testgreencity.ga/GreenCityClient/")
    self.driver.set_window_size(1680, 1050)
    self.driver.find_element(By.LINK_TEXT, "Eco news").click()
    element = self.driver.find_element(By.ID, "create-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "create-button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "label > .ng-invalid").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > .ng-invalid").send_keys("Hello world")
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tag-news:nth-child(5)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit")
    assert element.is_enabled() is True
  
